blank_issues_enabled: false
contact_links:
  - name: Discussions Forum
    url: https://github.com/ptr727/PlexCleaner/discussions
    about: Please use the Discussions forum for general questions and enhancement requests.
