"""Build the reduced (quickscan) corpus: shrink samples while PROVING every issue survives.

Each candidate clip is processed through the PlexCleaner image and must match the source's
`catalog.json` entry (generated by ``catalog_corpus.py``) on ALL of:

- State equality (the processing-decision fingerprint; catches issues with no log signature,
  e.g. timestamp-only-DTS files whose verify never logs a failed-execution line)
- detections superset (every ``<phrase> detected`` from the source re-surfaces)
- verify-error signatures superset (every captured error class re-surfaces)

Any miss -> the original is kept whole so no issue is ever lost.

Cutting strategy per file:

- default: head-clip ``[0, --seconds]`` (global properties + defects known to live in the head)
- region overrides (from the external rules file, located by ``locate_issue.py``): issue-localized
  windows for defects deep in the file
- the cutter ladder tries mkvmerge and ffmpeg cuts plus in-place IETF surgery, because the cutters
  have mirror-image side effects and only the prove-equivalence gate can pick the safe one
- ``artificial-container``: last-resort rung that re-muxes the head with the MP4 muxer under the
  ``.mkv`` name, reproducing a source that IS a renamed MP4 (a genuine MKV fails the gate here)
- relaxed acceptance (from the rules file): a named file may declare a bounded, benign delta in
  State, detections, or verify-error signatures, so a clip whose only shortfall is a documented
  downstream artifact still passes

The source corpus is READ-ONLY. Clips, work dirs, and outputs live under scratch / --out.

Media-specific data is NOT hard-coded here (that would embed private filenames); the region windows
AND the relaxed-acceptance overrides live in an external rules file next to the corpus. See
``reduction-rules.example.json``.

Modes:

- ``validate`` (default): cut + process each clip, compare to the catalog, report PASS/FAIL
- ``generate --out DIR``: same, but on PASS write the reduced file to DIR; on FAIL copy the
  original whole. Writes a reduced ``catalog.json`` with per-file decision, sizes, and issue sets.
"""

import argparse
import glob
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

from corpus_common import (
    SRC_DIR,
    classify_signature,
    hms,
    make_head_clip,
    parse_log,
    set_language_ietf,
    stem_of,
    strip_language_ietf,
)

# Default paths for the reference server; override on the command line for another environment.
SCRATCH = Path("/data/media/PlexCleaner/scratch-trim")
IMAGE = "docker.io/ptr727/plexcleaner:develop"
APP = "/PlexCleaner/Debug/PlexCleaner"

Region = tuple[int, int]


def load_regions(path: Path) -> dict[str, Region]:
    """Load issue-localized cut windows from the external rules file.

    The rules live WITH the media (never in source control, to keep private filenames out of the
    tree). Absent file -> no regions (head-clip everything); see ``reduction-rules.example.json``
    for the schema and ``locate_issue.py`` for generating entries.
    """
    if not path.exists():
        print(
            f"No rules file at {path} - regions empty (head-clip only). "
            f"See reduction-rules.example.json."
        )
        return {}
    data = json.loads(path.read_text())
    return {name: (int(r["start"]), int(r["end"])) for name, r in data.get("regions", {}).items()}


def load_accept(path: Path) -> dict[str, dict]:
    """Load relaxed-acceptance overrides from the external rules file.

    A file with a genuine, benign divergence between its full-source and best-clip processing (a
    downstream artifact of a repair that depends on full-file content, not the defect itself) would
    otherwise fail the strict gate and be kept whole. An ``accept`` entry declares the exact,
    bounded delta that is allowed for a NAMED rung, so the clip still ships while the divergence
    stays explicit. Absent file / no ``accept`` section -> strict gate everywhere. See
    ``reduction-rules.example.json`` for the schema.
    """
    if not path.exists():
        return {}
    raw = json.loads(path.read_text()).get("accept", {})
    # keep only real rules: drop the "_comment" metadata key (and any non-dict value) so the
    # relaxed count and the per-file lookup never treat a non-rule entry as an override
    return {k: v for k, v in raw.items() if not k.startswith("_") and isinstance(v, dict)}


def make_clip(
    src: Path, out: Path, seconds: int, regions: dict[str, Region], cutter: str = "mkvmerge"
) -> bool:
    """Cut a clip: a region window if the file has one in the rules, else a head-clip."""
    region = regions.get(src.name)
    if not region:
        return make_head_clip(src, out, seconds)
    start, end = region
    # escape the stem: corpus filenames contain glob metacharacters (e.g. brackets), which a raw
    # glob would read as character classes and mis-match, deleting the wrong files or none
    for p in out.parent.glob(glob.escape(out.stem) + ".*"):
        p.unlink()
    if cutter == "ffmpeg":
        # ffmpeg region cut gives cleaner timestamps at the cut boundary (a mkvmerge region cut can
        # add a spurious verify->repaired hiccup on remux-grade HEVC), at the usual IETF-strip cost
        subprocess.run(
            [
                "ffmpeg",
                "-hide_banner",
                "-loglevel",
                "error",
                "-ss",
                str(start),
                "-i",
                str(src),
                "-t",
                str(end - start),
                "-map",
                "0",
                "-c",
                "copy",
                "-avoid_negative_ts",
                "make_zero",
                "-bitexact",
                str(out),
            ],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    else:
        # mkvmerge region cut preserves timestamp defects (ffmpeg -copyts normalizes some away)
        subprocess.run(
            ["mkvmerge", "-o", str(out), "--split", f"parts:{hms(start)}-{hms(end)}", str(src)],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        if not out.exists():
            numbered = out.with_name(out.stem + "-001" + out.suffix)
            if numbered.exists():
                numbered.rename(out)
    return out.exists() and out.stat().st_size > 0


def make_artificial_container(src: Path, out: Path, seconds: int) -> bool:
    """Head-clip [0, seconds] with the MP4 muxer but keep the ``.mkv`` name.

    Reproduces a source that IS a renamed MP4: the byte stream is MP4 while the extension claims
    Matroska, which PlexCleaner detects as a container mismatch and remuxes. For a genuine MKV this
    produces an unrelated file that the prove-equivalence gate rejects, so it is only ever reached
    as the last ladder rung, after the real MKV cutters have failed.
    """
    # escape the stem: corpus filenames contain glob metacharacters (e.g. brackets), which a raw
    # glob would read as character classes and mis-match, deleting the wrong files or none
    for p in out.parent.glob(glob.escape(out.stem) + ".*"):
        p.unlink()
    proc = subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(src),
         "-t", str(seconds), "-map", "0", "-c", "copy", "-f", "mp4", str(out)],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )  # fmt: skip
    # this remux has clean success/fail semantics (unlike the mkv cutters, which can exit non-zero
    # yet leave a usable file), so require a clean exit as well as a non-empty output
    return proc.returncode == 0 and out.exists() and out.stat().st_size > 0


def process_clip(workdir: Path, settings_dir: Path) -> tuple[dict, dict[str, set[str]] | None]:
    """Process ``workdir/media`` through the image; return (parsed log map, {stem: state set}).

    Log + results go to ``workdir/out``, a SEPARATE mount: PlexCleaner deletes unwanted non-media
    files inside the media dir, so a log written there is deleted by the very run that wrote it.

    The State map is ``None`` when the run did not complete (missing or unreadable results file),
    so a failed run cannot be mistaken for an empty-State PASS and silently weaken the gate. A
    completed run always writes ``clip_results.json``, even when a file's State is empty.
    """
    media, out = workdir / "media", workdir / "out"
    out.mkdir(parents=True, exist_ok=True)
    uid, gid = os.getuid(), os.getgid()
    # Capture the container output so a failed run (crash or container that never starts) can be
    # diagnosed; on success it is discarded, on failure its tail is printed with the error below.
    proc = subprocess.run(
        [
            "docker",
            "run",
            "--rm",
            "--user",
            f"{uid}:{gid}",
            "--env",
            "TZ=America/Los_Angeles",
            "--volume",
            f"{media}:/media:rw",
            "--volume",
            f"{out}:/out:rw",
            "--volume",
            f"{settings_dir}:/config:ro",
            IMAGE,
            APP,
            "process",
            "--settingsfile=/config/PlexCleaner.json",
            "--logfile=/out/clip_process.log",
            "--mediafiles=/media",
            "--resultsfile=/out/clip_results.json",
            "--parallel",
            "--testsnippets",
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        errors="replace",
    )
    logmap = parse_log(out / "clip_process.log")
    results_file = out / "clip_results.json"
    if not results_file.exists():
        tail = "\n".join((proc.stdout or "").splitlines()[-15:])
        print(
            f"    run did not complete (exit {proc.returncode}); no results file:\n{tail}",
            file=sys.stderr,
        )
        return logmap, None  # run did not complete: not an empty result, a failure
    try:
        res = json.loads(results_file.read_text())
        results = res["Results"]["Results"]
    except (json.JSONDecodeError, KeyError, OSError) as e:
        print(f"    results file present but unreadable: {e}", file=sys.stderr)
        return logmap, None
    states: dict[str, set[str]] = {}
    for r in results:
        states[stem_of(os.path.basename(r["OriginalFileName"]))] = {
            s.strip() for s in (r.get("State") or "").split(",") if s.strip()
        }
    return logmap, states


def human(n: float) -> str:
    for unit in ("B", "K", "M", "G", "T"):
        if n < 1024:
            return f"{n:.0f}{unit}"
        n /= 1024
    return f"{n:.0f}P"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("sources", nargs="*", help="source basenames (default: all catalog files)")
    ap.add_argument("-s", "--seconds", type=int, default=60, help="head-clip length")
    ap.add_argument("--catalog", required=True, help="source catalog.json (from catalog_corpus.py)")
    ap.add_argument("--rules", help="external region rules file (default: next to --catalog)")
    ap.add_argument(
        "--settings",
        default="/data/media/PlexCleaner/RegressionTest",
        help="dir containing the PlexCleaner.json to process clips with",
    )
    ap.add_argument("--mode", choices=["validate", "generate"], default="validate")
    ap.add_argument("--out", help="output dir for the reduced set (generate mode)")
    args = ap.parse_args()

    if args.mode == "generate" and not args.out:
        sys.exit("generate mode requires --out DIR")

    catalog_path = Path(args.catalog)
    catalog = json.loads(catalog_path.read_text())
    entries = {e["file"]: e for e in catalog["files"]}
    rules_path = Path(args.rules) if args.rules else catalog_path.parent / "reduction-rules.json"
    regions = load_regions(rules_path)
    accept = load_accept(rules_path)
    print(f"Catalog      : {args.catalog}  ({len(entries)} files)")
    print(
        f"Head window  : {args.seconds}s   regions: {len(regions)}   "
        f"relaxed: {len(accept)}   mode={args.mode}\n"
    )

    sources = args.sources or sorted(entries)
    settings_dir = Path(args.settings)
    work_root = SCRATCH / "work"
    work_root.mkdir(parents=True, exist_ok=True)
    out_dir = Path(args.out) if args.out else None
    if out_dir:
        out_dir.mkdir(parents=True, exist_ok=True)

    manifest = []
    passes = fails = kept = 0
    print(f"{'FILE':54} {'SRC':>7} {'CLIP':>7} {'RATIO':>6}  RESULT")
    for name in sources:
        e = entries.get(name)
        src = SRC_DIR / name
        stem = stem_of(name)
        short = stem[:53]
        if e is None or not src.exists():
            miss = "CATALOG" if e is None else "SOURCE"
            print(f"{short:54} {'-':>7} {'-':>7} {'-':>6}  MISSING {miss}")
            continue
        gt_state = set(e["state"])
        gt_det = set(e["detections"])
        gt_subs = set(e["decode_subtypes"])
        ssz = src.stat().st_size

        # Cutter ladder: the cutters have mirror-image side effects, so try each and let the
        # prove-equivalence gate pick the one that preserves this file's issues. Surgical rungs
        # (in-place header edits, no remux): "*-noietf" re-injects the missing-IETF metadata defect
        # a mkvmerge cut repairs; "*-fixietf" sets IETF on an ffmpeg cut so the clip enters verify
        # metadata-clean and its timestamp defect drives the verify->repair chain.
        if name in regions:
            ladder = ["region", "region-noietf", "region-ffmpeg", "region-ffmpeg-fixietf"]
        elif src.suffix.lower() == ".mkv":
            # artificial-container is a last-resort rung: it only reproduces a renamed-MP4 source,
            # so it sits after every real MKV cutter and is reached only when they all fail.
            if gt_subs:
                # decode-signature file: the defect lives in the video packets, which an ffmpeg
                # stream-copy preserves faithfully. mkvmerge can pass the coarse gate while losing
                # the physical error shape, so try the ffmpeg cutters first for these.
                ladder = [
                    "ffmpeg", "ffmpeg-fixietf", "ffmpeg-tags", "mkvmerge", "mkvmerge-noietf",
                    "artificial-container",
                ]  # fmt: skip
            else:
                ladder = [
                    "mkvmerge", "mkvmerge-noietf", "ffmpeg-fixietf", "ffmpeg", "ffmpeg-tags",
                    "artificial-container",
                ]  # fmt: skip
        else:
            ladder = ["ffmpeg"]

        ok = False
        attempt: dict = {}
        attempts: list[dict] = []
        for cutter in ladder:
            fw = work_root / stem
            if fw.exists():
                shutil.rmtree(fw)
            (fw / "media").mkdir(parents=True)
            # cut a PRISTINE clip outside the media dir (processing mutates/renames the media copy;
            # the reduced corpus must ship the unprocessed clip with its issues intact)
            pristine = fw / name
            base = cutter.replace("-noietf", "").replace("-fixietf", "")
            if base.startswith("region"):
                made = make_clip(
                    src,
                    pristine,
                    args.seconds,
                    regions,
                    cutter="ffmpeg" if base == "region-ffmpeg" else "mkvmerge",
                )
            elif base == "artificial-container":
                made = make_artificial_container(src, pristine, args.seconds)
            else:
                made = make_head_clip(src, pristine, args.seconds, cutter=base)
            if made and cutter.endswith("-noietf"):
                made = strip_language_ietf(pristine)
            elif made and cutter.endswith("-fixietf"):
                made = set_language_ietf(pristine)
            if not made:
                attempt = {"cutter": cutter, "error": "CLIP FAILED"}
                continue
            # Source close to / shorter than the window -> ship VERBATIM: a cut remuxes, silently
            # repairing container/metadata defects, and already-short hand-made samples need no cut.
            verbatim = pristine.stat().st_size >= 0.5 * ssz
            if verbatim:
                shutil.copy2(src, pristine)
            elif (
                pristine.suffix.lower() == ".mkv"
                and base != "artificial-container"  # an MP4-in-mkv clip is not real Matroska
                and "ClearedTags" not in gt_state
            ):
                # both cutters add their own track tags (ffmpeg DURATION / mkvmerge statistics);
                # when the source had none, strip them in place (no remux, defects untouched) so
                # the clip does not pick up a spurious ClearedTags state
                subprocess.run(
                    ["mkvpropedit", str(pristine), "--tags", "all:"],
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
            shutil.copy2(pristine, fw / "media" / name)

            logmap, states = process_clip(fw, settings_dir)
            if states is None:
                # processing did not complete: a failed run must not pass as an empty result
                attempt = {"cutter": cutter, "error": "PROCESS FAILED"}
                continue
            cl = logmap.get(stem, {"detections": set(), "errors": set()})
            cl_state = states.get(stem, set())
            miss_d = gt_det - cl["detections"]
            # error equivalence at the SIGNATURE-CLASS level: raw lines embed per-site coordinates
            # (MB positions, picture numbers) and accumulate across every corrupt site in the
            # source, which a single-site clip can never string-match
            miss_e = gt_subs - classify_signature(cl["errors"])
            state_ok = cl_state == gt_state
            state_extra = cl_state - gt_state
            state_short = gt_state - cl_state
            strict_ok = state_ok and not miss_d and not miss_e
            # Relaxed acceptance: when strict fails, an ``accept`` rule for THIS file and THIS rung
            # may permit a bounded, documented delta (a benign downstream artifact) so the clip
            # still passes; the clip is accepted only if every shortfall stays within the bound.
            acc = accept.get(name)
            relaxed = False
            delta: dict = {}
            if acc and cutter == acc.get("method") and not strict_ok:
                over_short = state_short - set(acc.get("state_missing", []))
                over_extra = state_extra - set(acc.get("state_extra", []))
                over_d = miss_d - set(acc.get("detections_missing", []))
                over_e = miss_e - set(acc.get("signatures_missing", []))
                if not (over_short or over_extra or over_d or over_e):
                    relaxed = True
                    delta = {"missing": sorted(state_short), "extra": sorted(state_extra)}
            ok = strict_ok or relaxed
            attempt = {
                "cutter": cutter,
                "pristine": pristine,
                "csz": pristine.stat().st_size,
                "cl_state": cl_state,
                "miss_d": miss_d,
                "miss_e": miss_e,
                "state_ok": state_ok,
                "verbatim": verbatim,
                "relaxed": relaxed,
                "state_delta": delta,
            }
            attempts.append(attempt)
            if ok or verbatim:
                break  # verbatim is cutter-independent; retrying cannot change it

        csz = attempt.get("csz", ssz)
        ratio = f"{ssz / csz:.0f}x"
        result = (
            f"PASS ({attempt.get('cutter')}{', relaxed' if attempt.get('relaxed') else ''})"
            if ok
            else "FAIL"
        )
        print(f"{short:54} {human(ssz):>7} {human(csz):>7} {ratio:>6}  {result}")
        if not ok and "error" in attempt:
            print(f"    {attempt['error']}")
        elif not ok:
            for a in attempts:  # show every rung's failure so the per-cutter cause is visible
                delta_plus = sorted(a["cl_state"] - gt_state)
                delta_minus = sorted(gt_state - a["cl_state"])
                bits = []
                if delta_plus or delta_minus:
                    bits.append(f"state +{delta_plus} -{delta_minus}")
                if a["miss_d"]:
                    bits.append(f"miss_det={sorted(a['miss_d'])}")
                if a["miss_e"]:
                    bits.append(f"miss_sig={sorted(a['miss_e'])}")
                print(f"    [{a['cutter']}] {'; '.join(bits) or 'ok?'}")

        passes += ok
        fails += not ok
        if out_dir:
            dest = out_dir / name
            shutil.copy2(attempt["pristine"] if ok else src, dest)
            kept += not ok

        manifest.append(
            {
                "file": name,
                "decision": ("reduced" if ok else "kept-full")
                if out_dir
                else ("would-reduce" if ok else "would-keep"),
                "method": ("verbatim" if attempt.get("verbatim") else attempt.get("cutter", "-"))
                if ok
                else "kept-full",
                "source_bytes": ssz,
                "clip_bytes": csz if ok else ssz,
                "state_match": attempt.get("state_ok", False),
                "clip_state": sorted(attempt.get("cl_state", set())),
                "ground_state": sorted(gt_state),
                "missing_detections": sorted(attempt.get("miss_d", set())),
                "missing_signatures": sorted(attempt.get("miss_e", set())),
                # relaxed passes carry the documented delta they were accepted with, so a divergence
                # from ground stays explicit in the catalog rather than looking like a clean match
                **(
                    {"relaxed": True, "state_delta": attempt["state_delta"]}
                    if ok and attempt.get("relaxed")
                    else {}
                ),
            }
        )

    print(f"\nPASS={passes} FAIL={fails} kept-full={kept}")
    mpath = (out_dir or SCRATCH) / "catalog.json"
    mpath.write_text(
        json.dumps(
            {"schema": 1, "collection": "reduced", "file_count": len(manifest), "files": manifest},
            indent=2,
            ensure_ascii=False,
        )
    )
    print(f"catalog: {mpath}")


if __name__ == "__main__":
    main()
