name: Merge bot pull request action

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  merge-dependabot:
    name: Merge dependabot pull request job
    runs-on: ubuntu-latest
    # To prevent abuse, the PR must come from Dependabot and the PR must originate from this repository.
    if: >-
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository
    permissions:
      contents: write
      pull-requests: write

    steps:

      - name: Get dependabot metadata step
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      # Merge any non-NuGet update, e.g. GitHub Actions often updates v1 to v2.
      # Merge NuGet only for non-major updates, e.g. major updates may build but break functionality.
      - name: Merge pull request step
        if: >-
          (steps.metadata.outputs.package-ecosystem != 'nuget') ||
          (steps.metadata.outputs.update-type != 'version-update:semver-major')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
